name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch

env:
  ENV: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Upload file to EC2
      run: |
        # Ensure the directory exists on the EC2 instance
        ssh -o StrictHostKeyChecking=no ec2-user@54.174.124.249 "mkdir -p /home/ec2-user/my-static-site/_posts/"

        # Upload the file using SCP
        scp -o StrictHostKeyChecking=no "2025-01-27-welcome-to-jekyll.markdown" ec2-user@54.174.124.249:/home/ec2-user/my-static-site/_posts/

    - name: Run Jekyll on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.174.124.249 << 'EOF'
          cd /home/ec2-user/my-static-site
          # Start Jekyll and monitor its output
          bundle exec jekyll serve --host 0.0.0.0 --port 4000 2>&1 | tee jekyll_output.log
          
          # Check if the specific string is in the output
          if grep -q "Server running... press ctrl-c to stop." jekyll_output.log; then
            echo "Server is running. Exiting the script to prevent being stuck."
            exit 0
          fi
        EOF
